sudo: required
services: 
  - docker

before_install:
  - docker build -t rmedina0531/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true rmedina0531/react-test npm test

after_success:
  - docker build -t rmedina0531/multi-client ./client
  - docker built -t rmedina0531/multi-nginx ./nginx
  - docker built -t rmedina0531/multi-server ./server
  - docker built -t rmedina0531/multi-worker ./worker

  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rmedina0531/multi-client
  - docker push rmedina0531/multi-nginx
  - docker push rmedina0531/multi-server
  - docker push rmedina0531/multi-worker